SYSTEMD_DIR=/usr/lib/systemd/system

.PHONY: service rmservice restart

service:
	cp container-odm.service $(SYSTEMD_DIR)
	systemctl daemon-reload
	systemctl enable container-odm.service
	systemctl start container-odm.service

rmservice:
	systemctl stop container-odm.service
	systemctl disable container-odm.service
	rm -f "$(SYSTEMD_DIR)/container-odm.service"
	systemctl daemon-reload
	
restart:
	systemctl restart container-odm.service